src/Eppie.App/Eppie.App.Base/AppHead.xaml, src/Eppie.App/Eppie.App.Base/AppHead.xaml.cs, src/Eppie.App/Eppie.App.Mobile/Android/Main.Android.cs, src/Eppie.App/Eppie.App.Mobile/Android/MainActivity.Android.cs, src/Eppie.App/Eppie.App.Mobile/MacCatalyst/Main.maccatalyst.cs, src/Eppie.App/Eppie.App.Mobile/MacOS/Main.macOS.cs, src/Eppie.App/Eppie.App.Mobile/iOS/Main.iOS.cs, src/Eppie.App/Eppie.App.Skia.Gtk/Program.cs, src/Eppie.App/Eppie.App.Wasm/Program.cs, src/Eppie.App/Eppie.App/App.cs, src/Eppie.App/Eppie.App/AppResources.xaml, src/Eppie.App/Eppie.App/MainPage.xaml, src/Eppie.App/Eppie.App/MainPage.xaml.cs
License header is added to .cs and .xaml files
=> License header

.github/actions/build-project/action.yml, .github/actions/build-uno-project/action.yml, .github/actions/project-map/action.yml, .github/actions/setup-uno-platform/action.yml, .github/workflows/build.yml
add github composite-actions: 
- setup the Uno patform; 
- build the Uno project;
add project build workflow that runs on
- push to main branch
- create pull request
- manually
=> add github workflows

src/Eppie.App/Eppie.App.Base/AppHead.xaml, src/Eppie.App/Eppie.App.Base/AppHead.xaml.cs, src/Eppie.App/Eppie.App.Wasm/Program.cs, src/Eppie.App/Eppie.App/CommonApp.cs, src/Eppie.App/Eppie.App/Eppie.App.csproj, src/Eppie.App/Eppie.App/MainPage.xaml.cs
suppress CA1010;
fix CA1062;
fix CA1724;
=> Eppie.App.csproj: Analysis level 6.0-all

src/Eppie.App/Eppie.App.Wasm/Eppie.App.Wasm.csproj, src/Eppie.App/Eppie.App.Wasm/Program.cs
=> Eppie.App.Wasm.csproj: Analysis level 6.0-all

src/Eppie.App/Eppie.App.Mobile/Eppie.App.Mobile.csproj, src/Eppie.App/Eppie.App.Mobile/iOS/Info.plist, src/Eppie.App/Eppie.App.VSMac.slnf
=> add solution filter VSMac.slnf

.github/actions/setup-uno-platform/action.yml, .github/workflows/build.yml
- last manifest
- skip wsl, edgewebview2
- add platform targets
=> change setup-uno-platform

.github/workflows/build.yml
=> change build.yml

.github/workflows/build.yml
added getting the required .net sdk version from 'uno.ui.manifest.json'
=> Fix uno check

.github/actions/setup-uno-platform/action.yml, .github/actions/uno-check-manifest/action.yml, .github/workflows/build.yml, .github/workflows/codeql.yml
- added uno-check-manifest GitHub action
- updated uno-platform-setup GitHub action
- updated build.yml GitHub workflow
- changed: .Net Core version
- changed: versions of the GitHub actions 
- updated codeql.yml GitHub workflow
- changed: versions of the GitHub actions
- added: uno-platform-setup GitHub action for csharp
=> Fixed: Building the Uno Platform project inside GitHub workflow.

.github/dependabot.yml
- 'github-actions' package-ecosystem was added
=> 'github-actions' package-ecosystem

.github/ISSUE_TEMPLATE/10_bug_report.yml, .github/ISSUE_TEMPLATE/20_feature_request.yml, .github/ISSUE_TEMPLATE/30_general_task.yml
- added new task template
- renamed existing issue templates
- re-sorted the templates
=> Task template

.github/dependabot.yml
Related to #304 
- change dependabot prefixes
- change the labels for the `github-actions` ecosystem
> [!NOTE]
>
>
> - `docs` - changes in **documentation** …
=> chore: change the dependabot configuration file

.github/pull_request_template.md
Related to #304
Added `./.github/pull_request_template.md` template with the following information:
- Related issues
- Description of the pull request
- Other Information
-  Pull Request Checklist
The template also contains notes about the labels.
> [!NOTE]
>
>
> - `build` - changes related to …
=> docs(template): add pull request template

.github/ISSUE_TEMPLATE/10_bug_report.yml
- Include new sections 'Current behavior', 'Expected Behavior' and 'Environment'
- Change the descriptions, headers and placeholders of the current sections
- Change the default labels
> [!NOTE]
>
> …
=> docs(template): change 'Bug Report' template

.github/ISSUE_TEMPLATE/20_feature_request.yml
- Include sections 'Additional Information', 
- Change the descriptions, titles and placeholders of the current sections
- Change the template options
> [!NOTE]
>
> …
=> docs(template): change 'Feature Request' template

.github/ISSUE_TEMPLATE/30_general_task.yml
- Change the descriptions, titles and placeholders of the template sections
- Change the template options
> [!NOTE]
>
>
> - `docs` - changes …
=> docs(template): change 'General Task' template

.github/release.yml
Related to Eppie-io/Eppie-App#303
1. Add `./.github/release.yml` template with the following categories:
- Breaking Changes
- New Features
- Bug Fixes
- Performance Improvements
- Localization Changes
2. Exclude pull requests created by @dependabot from release notes
3. Exclude pull request with label `ignore-for-release` from release notes
> [!NOTE]
>
>
> - …
=> docs(template): add 'Release Notes' template

.github/pull_request_template.md
Сorrect the label name in the pull request note
> [!NOTE]
>
>
> …
=> docs(template): change 'Pull Request' template

.github/ISSUE_TEMPLATE/10_bug_report.yml, .github/ISSUE_TEMPLATE/20_feature_request.yml, .github/ISSUE_TEMPLATE/30_general_task.yml, .github/dependabot.yml, .github/pull_request_template.md, .github/release.yml, .gitignore, src/Eppie.App/Eppie.App.Shared/Strings/pl/Resources.resw
Related to #296 
> [!NOTE]
>
> …
=> chore: sync branch

.github/dependabot.yml
Related to #304
Change the prefix for the ecosystem "github-actions"
> [!NOTE]
>
> …
=> chore: change dependabot prefix

.github/configurations/build.json, .github/workflows/build.yml
- fix the build of WinUI and UWP projects
- change the name of the 'build' job
> [!NOTE]
>
> …
=> ci: change build workflow

source/Eppie.App/Directory.Build.props, source/Eppie.App/Eppie.App.ViewModels/Eppie.App.ViewModels.csproj, source/Eppie.App/Eppie.App/App.xaml.cs, source/Eppie.App/Eppie.App/Models/AppConfig.cs, source/Eppie.App/Eppie.App/Platforms/WebAssembly/Program.cs
Related to Eppie-io/Eppie-App#347
Remove nullable value types.
> [!NOTE]
>
>
> - …
=> build: disable the 'nullable' feature

source/Eppie.App/.editorconfig, source/Eppie.App/Eppie.App.sln, source/Eppie.App/Eppie.App/App.xaml.cs, source/Eppie.App/Eppie.App/Eppie.App.csproj, source/Eppie.App/Eppie.App/Models/AppConfig.cs, source/Eppie.App/Eppie.App/Platforms/Android/Main.Android.cs, source/Eppie.App/Eppie.App/Platforms/Android/MainActivity.Android.cs, source/Eppie.App/Eppie.App/Platforms/Desktop/Program.cs, source/Eppie.App/Eppie.App/Platforms/MacCatalyst/Main.maccatalyst.cs, source/Eppie.App/Eppie.App/Platforms/WebAssembly/Program.cs, source/Eppie.App/Eppie.App/Platforms/iOS/Main.iOS.cs
Related to #331
- Enforce code style
- Define the rules `csharp_style_namespace_declarations`, **IDE0160** and **IDE0161**.
> [!NOTE]
>
>
> - `docs` - changes …
=> refactor: systematize the namespace declaration 

.github/configurations/build.json
Related to Eppie-io/Eppie-App#332
- Fix error **UNOB0008** 
> [!NOTE]
>
>
> - …
=> ci: fix build workflow

.github/workflows/codeql.yml
Related to Eppie-io/Eppie-App#332
- Correct the path to the action `finebits/github-actions/devhub/uno-platform/setup`
- Change the versions of actions
> [!NOTE]
>
> …
=> ci: fix codeql workflow

source/Eppie.App/Directory.Packages.props, source/Eppie.App/Eppie.App.Shared/Behaviors/ClipboardBehaviorBase.cs, source/Eppie.App/Eppie.App.Shared/Behaviors/CopyToClipboardBehavior.cs, source/Eppie.App/Eppie.App.Shared/Behaviors/DialogBehavior.cs, source/Eppie.App/Eppie.App.Shared/Behaviors/FileBehavior.cs, source/Eppie.App/Eppie.App.Shared/Behaviors/ItemClickCommandBehavior.cs, source/Eppie.App/Eppie.App.Shared/Behaviors/ListViewItemClickBehavior.cs, source/Eppie.App/Eppie.App.Shared/Behaviors/ObjectToFileBehavior.cs, source/Eppie.App/Eppie.App.Shared/Behaviors/PasteFromClipboardBehavior.cs, source/Eppie.App/Eppie.App.Shared/Behaviors/TreeViewItemInvokeBehavior.cs, source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, source/Eppie.App/Eppie.App/Eppie.App.csproj
Related to #347
- Move files from Behaviors to Eppie.App.Shared.
- Correct styles: whitespace formatting, file encoding.
> [!NOTE]
>
> …
=> chore: move Behaviors to Eppie.App.Shared

source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.Uno/global.json, source/Eppie.App/global.json
Close #358
Update the **Uno.Sdk** to version 5.4.10
> [!NOTE]
>
>
> - `chore` - …
=> build: update Uno.Sdk

source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.UWP/Eppie.App.Converters.UWP.csproj, source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.Uno/Eppie.App.Converters.Uno.csproj, source/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs, source/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs, source/Eppie.App/Eppie.App.Shared/App.xaml, source/Eppie.App/Eppie.App.Shared/App.xaml.cs, source/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.Uno.cs, source/Eppie.App/Eppie.App.Shared/Behaviors/TreeViewItemInvokeBehavior.cs, source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
Related to #347
- add the UWP app launch
- split the code in the file **App.xaml.cs** into common and platform-specific
> [!NOTE]
>
> …
=> feat: add the UWP app launch

source/Eppie.App/Eppie.App.Shared/Behaviors/TreeViewItemInvokeBehavior.cs
Related to Eppie-io/Eppie-App#382
Change the control type from **Windows.UI.Xaml.Controls.TreeView** to **Microsoft.UI.Xaml.Controls.TreeView**
> [!NOTE]
>
> …
=> fix: fix TreeView behavior

source/Eppie.App/.editorconfig
Related to Eppie-io/Eppie-App#331
Change the indent size in **xaml** files to 4
> [!NOTE]
>
>
> - `docs` - changes in **documentation** or just **comments** …
=> chore: change xaml indent rule

source/Eppie.App/Eppie.App.Shared/Behaviors/ItemClickCommandBehavior.cs, source/Eppie.App/Eppie.App.Shared/Styles/NavigationViewStyle.xaml, source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs
Related to #382
- Use the **NavigationView** control from the **Microsoft.UI.Xaml.Controls** 
- Reorganize the NavigationViewItem
- Change NavigationView style
> [!NOTE]
>
> …
=> fix: replace NavigationView control

source/Eppie.App/Eppie.App.UWP/Package.appxmanifest, source/Eppie.App/Eppie.App.UWP/Properties/AssemblyInfo.cs, source/Eppie.App/Eppie.App/Package.appxmanifest
Related to https://github.com/Eppie-io/Eppie-App/issues/328
App information was added
> [!NOTE]
>
> …
=> chore: app information was added

.gitignore, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.shproj, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Properties/AssemblyInfo.cs, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Properties/Eppie.App.UI.UWP.rd.xml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json, source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, source/Eppie.App/Eppie.App.sln, source/Eppie.App/Eppie.App/Eppie.App.csproj
Related to Eppie-io/Eppie-App#382
- Add **Eppie.App.UI.Shared** Shared project
- Add **Eppie.App.UI.Uno** Uno Platform Library project
- Add **Eppie.App.UI.UWP** Universal Windows Class Library project
> [!NOTE]
>
> …
=> refactor: add Eppie.App.UI.* projects

source/Eppie.App/Eppie.App.Shared/Resources/Strings/en/Resources.resw, source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml, source/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
N/A
Support development button was added.
> [!NOTE]
>
> …
=> feat: add a support development button

source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, source/Eppie.App/Eppie.App.Shared/Services/PurchaseService.cs, source/Eppie.App/Eppie.App.Shared/Views/BasePage.cs, source/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs, source/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs, source/Eppie.App/Eppie.App.ViewModels/Services/IPurchaseService.cs
N/A
Implement SupportDevelopmentAsync() function
> [!NOTE]
>
>
> - `chore` - …
=> feat: implement SupportDevelopmentAsync() function

source/Eppie.App/.editorconfig
Related to #331
Set the severity value to **error** for the **formatting rule (IDE0055)** 
> [!NOTE]
>
> …
=> build: add IDE0055 formatting rule

source/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.cs, source/Eppie.App/Eppie.App.Shared/Controls/EmailProvidersListControl.xaml.cs, source/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml.cs, source/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml.cs, source/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml.cs, source/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml.cs, source/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml.cs, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/ValueToBoolConverter.cs, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.cs, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Properties/AssemblyInfo.cs, source/Eppie.App/Eppie.App.ViewModels/AboutPageViewModel.cs, source/Eppie.App/Eppie.App.ViewModels/Services/ILocalSettingsService.cs, source/Eppie.App/Eppie.App/GlobalUsings.cs, source/Eppie.App/Eppie.App/Platforms/Android/Main.Android.cs, source/Eppie.App/Eppie.App/Platforms/Android/MainActivity.Android.cs
Related to #377
Code cleaning
> [!NOTE]
>
> …
=> refactor: code cleaning

source/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageControl.xaml.cs, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/MessageControl.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
Related to #382
Create a platform specific **MessageControl**.
> [!NOTE]
>
>
> - …
=> feat: create MessageControl

source/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EditMessageControl.xaml.cs, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/EditMessageControl.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/RichTextEditor.cs, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/EditMessageControl.xaml
Related to Eppie-io/Eppie-App#382
Create a platform specific **EditMessageControl**.
> [!NOTE]
>
> …
=> feat: create EditMessageControl

source/Eppie.App/Directory.Packages.props, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailsInputControl.xaml.cs, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/EmailsInputControl.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/EmailsInputControl.xaml, source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
Related to Eppie-io/Eppie-App#382
- Add platform specific changes to the **EmailsInputControl**
- Use **CommunityToolkit.Uwp.Controls.TokenizingTextBox**
> [!NOTE]
>
> …
=> feat: change EmailsInputControl

.gitignore, source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Eppie.App.Resources.Shared.projitems, source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Eppie.App.Resources.Shared.shproj, source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.UWP/Eppie.App.Resources.UWP.csproj, source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.UWP/Properties/AssemblyInfo.cs, source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.UWP/Properties/Eppie.App.Resources.UWP.rd.xml, source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/Eppie.App.Resources.Uno.csproj, source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/global.json, source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, source/Eppie.App/Eppie.App.sln, source/Eppie.App/Eppie.App/Eppie.App.csproj
Related to Eppie-io/Eppie-App#411
- Create **Eppie.App.Resources.Shared**, **Eppie.App.Resources.Uno**, **Eppie.App.Resources.UWP** libraries
- Change **AssemblyName**, **RootNamespace**
- Add References to **Eppie.App.Resources.Uno**, **Eppie.App.Resources.UWP** libraries
> [!NOTE]
>
>
> - …
=> refactor: create Eppie.App.Resources library

source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Eppie.App.Resources.Shared.projitems, source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/StringProvider.cs, source/Eppie.App/Eppie.App.Shared/Models/NotificationManager.cs, source/Eppie.App/Eppie.App.Shared/Services/LocalizationService.cs, source/Eppie.App/Eppie.App.Shared/Services/MessageService.cs, source/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml.cs, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/LanguageSelectionControl.xaml.cs, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/BoolToValueConverter.cs
Related to Eppie-io/Eppie-App#411
- Create `StringProvider` that loads strings from the **Eppie.App.Resources** library
- Replace `ResourceLoader` with `StringProvider`
> [!NOTE]
>
> …
=> fix: fix loading of string resources in code

source/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/DecentralizedAccountSettingsPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/IdentityManagerPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml, source/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml, source/Eppie.App/Eppie.App.Shared/Views/PasswordPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/PgpKeyPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/PgpKeysPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/ProtonAccountSettingsPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml, source/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml, source/Eppie.App/Eppie.App.Shared/Views/SelectEmailProviderPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml, source/Eppie.App/Eppie.App.Shared/Views/WelcomePage.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AccountSettingsControl.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ContactsListControl.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/DecentralizedAccountSettingsControl.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageListControl.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NavPanelTabControl.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/PasswordControl.xaml, source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ProtonAccountSettingsControl.xaml
Related to Eppie-io/Eppie-App#411
Use string resources from **Eppie.App.Resources** library
> [!NOTE]
>
> …
=> fix: correct x:Uid keys

source/Eppie.App/Eppie.App.UWP/Package.appxmanifest, source/Eppie.App/Eppie.App/Package.appxmanifest
Close Eppie-io/Eppie-App#417
Write all languages ​​to **Package.appxmanifest** files.
> [!NOTE]
>
> …
=> fix: add resources to manifest

.github/workflows/build.yml, .github/workflows/codeql.yml
Related to #296
Fix Conflicts:
- .github/workflows/build.yml
- .github/workflows/codeql.yml
> [!NOTE]
>
> …
=> chore: merge branch 'main' into feature/296-upgrading-to-uno-platform-5

.github/workflows/build.yml, .github/workflows/format.yml
Close Eppie-io/Eppie-App#343
Remove unused branche-triggers
> [!NOTE]
>
>
> - …
=> ci: remove unused triggers

.gitignore, .gitmodules, src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, src/Eppie.App/Eppie.App.sln, src/Eppie.App/Eppie.App/Eppie.App.csproj
=> test: add tests

.gitmodules, src/Eppie.App/Eppie.App.sln
=> build: fix build

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/format.yml, src/Eppie.App/Directory.Packages.props, src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/Eppie.App.Resources.Uno.csproj, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj, src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, src/Eppie.App/Eppie.App/Eppie.App.csproj
Related to #432
- Update vulnerable packages
- Update submodules
- Add dotnet version 9 in CI scripts
- Add **WindowsSdkPackageVersion** to Uno projects
> [!NOTE]
>
> …
=> build: fix build project

src/Eppie.App/Directory.Packages.props, src/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs, src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs, src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml, src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
N/A
Add Microsoft Engagement Framework
> [!NOTE]
>
> …
=> feat: add Microsoft Engagement Framework

src/Eppie.App/Directory.Packages.props, src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/Eppie.App.Resources.Uno.csproj, src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/global.json, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json, src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, src/Eppie.App/Eppie.App/Eppie.App.csproj, src/Eppie.App/global.json
Related to #432
- Update **Uno.Sdk** to 5.5.43
- Remove **WindowsSdkPackageVersion** option
- Remove **System.IO.Packaging** nuget which is currently used from **Uno.Sdk**
> [!NOTE]
>
> …
=> build(deps): update Uno SDK

.github/actions/install-prerequisites/action.yml, .github/configurations/build.json, .github/configurations/workload.json, .github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/format.yml, src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/Eppie.App.Resources.Uno.csproj, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj, src/Eppie.App/Eppie.App/Eppie.App.csproj, src/Eppie.App/global.json
Related to #432
- Fix build.yml
- Fix codeql.yml
- Add install-prerequisites action
> [!NOTE]
>
> …
=> ci: fix CI build

.github/workflows/build.yml
- Refactoring
- Change the scheduled build configuration
- Change action name
> [!NOTE]
>
> …
=> ci: change build script

src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, src/Eppie.App/Eppie.App.Shared/Services/DragAndDropService.cs, src/Eppie.App/Eppie.App.Shared/Services/StorageItemsService.cs, src/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs, src/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs, src/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml, src/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/FileBehavior.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MailBoxesListControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MailBoxesListControl.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageListControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageListControl.xaml.cs, src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/Models/MailBoxesModel.cs, src/Eppie.App/Eppie.App.ViewModels/Services/IDragAndDropService.cs
N/A
Add drag and drop to move letters.
> [!NOTE]
>
> …
=> feat: add drag and drop to move letters

src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs, src/Eppie.App/Eppie.App.ViewModels/AllMessagesPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/ContactMessagesPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/FolderMessagesPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/IdentityManagerPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/NewMessagePageViewModel.cs
N/A
Improve error handling.
> [!NOTE]
>
> …
=> refactor: improve error handling

src/Eppie.App/Eppie.App.ViewModels/NewMessagePageViewModel.cs
N/A
Fix update draft message.
> [!NOTE]
>
> …
=> fix: fix update draft message

src/Eppie.App/Eppie.App.Shared/Services/MessageService.cs
N/A
Add exception info
> [!NOTE]
>
> …
=> refactor: add exception info

src/Eppie.App/Eppie.Authorization.OAuth2/TokenRefresher.cs
N/A
Add error handling.
(cherry picked from commit 49823b8a9122b4af2023fb469911267b55c02e03)
> [!NOTE]
>
> …
=> refactor: add error handling

src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/en/Resources.resw, src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/zh-CN/Resources.resw
Related to https://github.com/Eppie-io/Eppie-App/issues/302
Add Chinese simplified.
> [!NOTE]
>
> …
=> feat(lang): add Chinese simplified

src/Eppie.App/Directory.Packages.props, src/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.cs, src/Eppie.App/Eppie.App.Shared/Services/MessageService.cs, src/Eppie.App/Eppie.App.ViewModels/AccountSettingsPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/Eppie.App.ViewModels.csproj, src/Eppie.App/Eppie.App.ViewModels/Extensions/CredentialExtension.cs, src/Eppie.App/Eppie.Authorization.OAuth2/TokenRefresher.cs
N/A
Read outlook email address from `id_token`
> [!NOTE]
>
>
> - `chore` - …
=> fix: fix outlook login

src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/zh-CN/Resources.resw
N/A
Fix strings.
> [!NOTE]
>
> …
=> fix: fix strings

src/Eppie.App/Eppie.App.ViewModels/BaseAccountSettingsPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/Models/MailBoxesModel.cs
N/A
Fix accounts update.
> [!NOTE]
>
> …
=> fix: fix accounts update

src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/global.json, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json, src/Eppie.App/global.json
Related to #432
Update **Uno.Sdk** to 5.5.56
> [!NOTE]
>
>
> - `chore` - …
=> build(deps): update uno sdk 5.5.56

src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs, src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
N/A
Open identity manager pane if accounts list is empty.
> [!NOTE]
>
>
> - …
=> fix: open identity manager pane if accounts list is empty

src/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.Win.cs, src/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.cs, src/Eppie.App/Eppie.App.Shared/Authorization/AuthenticationBroker.UWP.cs, src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, src/Eppie.App/Eppie.App.UWP/Authorization/AuthConfig.UWP.cs
Resolve #501
- Add **AuthenticationBroker** based on **HTTPListener** and use **Web Browser**
Now we need to set up mail authorizations for **net9.0-windows10.0** project, as well as for the **eppie-cli** project with the ability to redirect to **localhost**.
> [!NOTE]
>
>
> - `build` - changes …
=> feat: add authorization to the windows project

.github/ISSUE_TEMPLATE/10_bug_report.yml, .github/ISSUE_TEMPLATE/20_feature_request.yml, .github/ISSUE_TEMPLATE/30_general_task.yml
- Add **Type** option to the github issue templates
- Change **Subtasks** section in **Task** template.
> [!NOTE]
>
> …
=> docs: update the github issue templates

.github/ISSUE_TEMPLATE/30_general_task.yml
- Correct the offset of the element in yaml.
> [!NOTE]
>
>
> - …
=> docs: correct task template

src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/global.json, src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json, src/Eppie.App/global.json
Resolves #505
- Update **Uno.SDK**;
- Change obsolete method.
> [!NOTE]
>
>
> - …
=> build: update uno to 5.6.20

src/Eppie.App/Eppie.App.Shared/Models/NotificationManager.cs
#518
Fix: unread badge.
> [!NOTE]
>
> …
=> fix: unread badge

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.cs
N/A
Fix: escape angle brackets.
> [!NOTE]
>
> …
=> fix: escape angle brackets

src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, src/Eppie.App/Eppie.App.ViewModels/MessagePageViewModel.cs, src/Eppie.App/Eppie.App/Authorization/AuthConfig.Win.cs, src/Eppie.App/Eppie.App/Package.appxmanifest
N/A
Fix: prepare for store distribution.
> [!NOTE]
>
> …
=> fix: prepare for store distribution

src/Eppie.App/Eppie.App.Shared/Services/LocalSettingsService.cs, src/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml.cs, src/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml.cs, src/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml.cs, src/Eppie.App/Eppie.App.ViewModels/AllMessagesPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/ContactMessagesPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/FolderMessagesPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/Services/ILocalSettingsService.cs
https://github.com/Eppie-io/Eppie-App/issues/524
Fix: save emails filter
> [!NOTE]
>
> …
=> fix: save emails filter

src/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs, src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs, src/Eppie.App/Eppie.App.Shared/App.xaml.cs, src/Eppie.App/Eppie.App.Shared/Services/MessageService.cs, src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Tools/UITools.cs
N/A
- Set XamlRoot property
[Using ContentDialog](https://platform.uno/docs/articles/features/dialogs.html?tabs=mvvm%2Cxaml#using-contentdialog)
> [!NOTE]
>
> …
=> fix: set XamlRoot before showing ContentDialog

src/Eppie.App/Eppie.App.Shared/Services/MessageService.cs, src/Eppie.App/Eppie.App.ViewModels/AccountSettingsPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/IdentityManagerPageViewModel.cs
N/A
Fix: update accounts.
> [!NOTE]
>
> …
=> fix: update accounts

src/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.Uno.cs
References #500
- Change default auth configuration
> [!NOTE]
>
>
> - `chore` - …
=> feat: add deafult auth config

.github/workflows/publish-macos.yml
N/A
- Add a workflow for publishing an unsigned Mac Catalyst app.
- [Run the unsigned app](https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/deployment/publish-unsigned?view=net-maui-9.0#run-the-unsigned-app)
> [!NOTE]
>
>
> - `build` - changes related to **the build of the project** and …
=> ci: publish macos workflow

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EditMessageControl.xaml.cs
Related to #382
- Correct the EditMessageControl bindings
> [!NOTE]
>
>
> - …
=> fix(ui): fix EditMessageControl properties

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/CommandArgumentBehavior.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
Related to #562
- Add `CommandArgumentBehavior`
> [!NOTE]
>
>
> - `chore` - …
=> feat(ui): add ui behavior

src/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs, src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs, src/Eppie.App/Eppie.App.Shared/App.xaml.cs, src/Eppie.App/Eppie.App.Shared/Services/AIService.cs, src/Eppie.App/Eppie.App.Shared/Services/FileOperationProvider.cs, src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs
Closes #560
- Add **MainWindow** static property
- Create item pickers using **builders** instead of the `new` operator
> [!NOTE]
>
> …
=> fix: item picker winui

src/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml, src/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MailBoxesListControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageListControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/MessageControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml
Related to #377
Format xaml files
> [!NOTE]
>
> …
=> style: format xaml files

src/Eppie.App/Eppie.App.ViewModels/Common/NewMessageData.cs
N/A
Fix MessageReceiver.
> [!NOTE]
>
> …
=> fix: MessageReceiver

.github/workflows/xaml-style-check.yml
- add xaml style check workflow
> [!NOTE]
>
>
> - `chore` - …
=> ci: add xaml style check workflow

src/Eppie.App/Eppie.App.Shared/Services/AIService.cs, src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, src/Eppie.App/Eppie.App/Eppie.App.csproj
=> build: fix macOS

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MailBoxesListControl.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/NavPanelTabControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/NavPanelTabControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
Related to #382 #587
Hide **MailBoxesListControl** on maccatalyst platform
> [!NOTE]
>
> …
=> fix: tabview crash on maccatalyst

.github/actions/install-prerequisites/action.yml
- Change xcode version to 16.2
> [!NOTE]
>
>
> - `chore` - …
=> ci: fix ios build

src/Eppie.App/Eppie.AI/Service.cs, src/Eppie.App/Eppie.AI/Utils/GenAIModel.cs, src/Eppie.App/Eppie.App.Shared/Models/NotificationManager.cs, src/Eppie.App/Eppie.App.Shared/Services/ErrorHandler.cs, src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs, src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml.cs, src/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml.cs, src/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/LanguageSelectionControl.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/RichTextEditor.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/BoolToValueConverter.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.cs, src/Eppie.App/Eppie.App.UWP/Properties/AssemblyInfo.cs, src/Eppie.App/Eppie.App.ViewModels/AllMessagesPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/ContactMessagesPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/FolderMessagesPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/IdentityManagerPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/LocalAIAgentSettingsPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/MessagePageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/Models/MailBoxesModel.cs, src/Eppie.App/Eppie.App.ViewModels/Services/IDragAndDropService.cs, src/Eppie.App/Eppie.App/Models/BrandLoader.cs, src/Eppie.App/Eppie.App/Services/PurchaseService.cs
=> refactor: clean code

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json, src/Eppie.App/global.json
Close #505
- Update **Uno.Sdk** version to 5.6.45
> [!NOTE]
>
>
> - `chore` - …
=> build: update Uno.Sdk version

src/Eppie.App/Eppie.App.Shared/Services/AIService.cs, src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/SelectServicePageViewModel.cs
N/A
Add MessageIsNotExistException.
> [!NOTE]
>
> …
=> fix: add MessageIsNotExistException

src/Eppie.App/Eppie.App/Eppie.App.csproj
N/A
- Remove Eppie.AI project from Eppie.App
- Remove AI related packages from Eppie.App
- Fix the Eppie.App(WinAppSDK) start
> [!NOTE]
>
>
> - `docs` - …
=> build: disable Eppie.AI in uno apps

src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw, src/Eppie.App/Eppie.App.Shared/Services/AIService.cs, src/Eppie.App/Eppie.App.Shared/Views/LocalAIAgentSettingsPage.xaml, src/Eppie.App/Eppie.App.ViewModels/LocalAIAgentSettingsPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/MessagePageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs
N/A
Add get message body high priority async.
> [!NOTE]
>
>
> - `chore` - …
=> fix: add get message body high priority async

src/Eppie.App/Eppie.App.Shared/Models/NotificationManager.cs
N/A
Fix notification.
> [!NOTE]
>
>
> - `chore` - something that **doesn't fit** …
=> fix: fix notification

.github/configurations/publish-desktop-binaries.json, .github/configurations/publish-desktop-span.json, .github/configurations/publish.json, .github/workflows/publish-desktop-binaries.yml, .github/workflows/publish.yml
-  Add the publish script with the following features:
- Publish desktop binaries for Linux, Windows and macOS
- Save Artifacts
- Upload assets to Release
> [!NOTE]
>
> …
=> ci: add publish workflow

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageControl.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/MessageControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml
Related to #372 
Fix open default browser.
> [!NOTE]
>
> …
=> fix: fix open default browser

src/Eppie.App/Eppie.App.Shared/Services/ClipboardProvider.cs, src/Eppie.App/Eppie.App.Shared/Services/MessageService.cs, src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs
N/A
Fix SetClipboardContent.
> [!NOTE]
>
> …
=> fix: fix SetClipboardContent

src/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/DecentralizedAccountSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/ProtonAccountSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml, src/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml
N/A
Fix Expander.
> [!NOTE]
>
> …
=> fix: fix Expander

README.md
> [!NOTE]
>
>
> - `chore` - something that **doesn't fit** the other possible …
=> docs: minor fixes in README.md

.github/configurations/publish-desktop-binaries.json, .github/workflows/publish-desktop-binaries.yml, .github/workflows/publish.yml, src/Eppie.App/Directory.Build.targets
- Add linux-arm64 binaries
- Add macos-arm64 binaries
- Fix macos-x64 binaries
> [!NOTE]
>
> …
=> ci: publish desktop arm64 binaries

src/Eppie.App/Eppie.App.Resources.Shared/Eppie.App.Resources.Shared.projitems, src/Eppie.App/Eppie.App.Resources.Shared/Strings/nl/Resources.resw, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/nl/Controls.resw, src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, src/Eppie.App/Eppie.App.UWP/Resources/Strings/nl/App.Resources.resw, src/Eppie.App/Eppie.App/Resources/Strings/nl/App.Resources.resw
=> feat: add dutch

.github/actions/assign-version/action.yml, .github/configurations/publish-desktop-binaries.json, .github/workflows/publish-desktop-binaries.yml, src/Eppie.App/Directory.Build.targets
Close #613
- Create `assign-version` action
- Add the ability to change the package version from **yml** script
> [!NOTE]
>
> …
=> ci: set package version

.github/actions/assign-version/action.yml, .github/workflows/publish-desktop-binaries.yml
- Add **ApplicationVersion** publish option
- Add **ApplicationDisplayVersion** publish option
> [!NOTE]
>
> …
=> ci: set ApplicationVersion option

.github/configurations/publish-desktop-span.json, .github/workflows/publish-desktop-snap.yml, .github/workflows/publish.yml
- Add Linux Desktop snap publish yml-script
> [!NOTE]
>
>
> - …
=> ci: add publish snap yml-script

.github/configurations/publish-desktop-binaries.json, .github/configurations/publish-desktop-span.json, .github/configurations/publish-mac-catalyst-pkg.json, .github/workflows/publish-desktop-binaries.yml, .github/workflows/publish-desktop-snap.yml, .github/workflows/publish-mac-catalyst-pkg.yml, .github/workflows/publish.yml, src/Eppie.App/Directory.Build.targets
- Add `dotnet-verbosity` yml input
- Add dynamic workflow name
- Refactor the deletion of **.pdb** files 
- Refactor the launch of publication jobs
> [!NOTE]
>
> …
=> ci: refactor publish scripts

.github/actions/assign-version/action.yml
- Change the format of the numeric version
> [!NOTE]
>
>
> - …
=> ci: change version format

.github/configurations/publish-desktop-app.json, .github/configurations/publish-desktop-binaries.json, .github/configurations/publish.json, .github/workflows/publish-desktop-app.yml, .github/workflows/publish-desktop-snap.yml, .github/workflows/publish.yml, src/Eppie.App/Eppie.App/Eppie.App.csproj
- Add macOS app package publishing
- Rename workflows
- Disable Mac Catalyst implicit publishing
> [!NOTE]
>
> …
=> ci: publish desktop macOS app

README.md
- Add link to Desktop Linux x64 span package
- Add link to Desktop macOS x64 app package
- Add link to Desktop macOS arm64 app package
> [!NOTE]
>
> …
=> docs: add asset links to readme

src/Eppie.App/Directory.Packages.props, src/Eppie.App/Eppie.AI/Service.cs, src/Eppie.App/Eppie.AI/Utils/GenAIModel.cs
Updates projects to use the latest version of Microsoft.Extensions.AI.Abstractions.
> [!NOTE]
>
> …
=> build(deps): Bump to M.E.AI 9.4.0-preview.1.25207.5

src/Eppie.App/Eppie.App.Shared/Services/AIService.cs, src/Eppie.App/Eppie.App.Shared/Views/LocalAIAgentSettingsPage.xaml
N/A
• Updated the ReplyToMessage method to use the text parameter and add the "RE(AI): " prefix to the message subject.
• Modified the interface structure in LocalAIAgentSettingsPage.xaml: buttons and the loading indicator are now placed in a StackPanel, improving layout.
• Added a hyperlink to the documentation for setting up the AI agent.
> [!NOTE]
>
>
> - …
=> fix: changes in message handling and interface

src/Eppie.App/Eppie.App.Shared/Services/AIService.cs, src/Eppie.App/Eppie.App.Shared/Views/LocalAIAgentSettingsPage.xaml, src/Eppie.App/Eppie.App.ViewModels/BaseAccountSettingsPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/ProtonAccountSettingsPageViewModel.cs
N/A
• Added a catch block in the BaseAccountSettingsPageViewModel.cs method to handle AuthorizationException, which throws NeedAdditionalAuthInfo. 
• Overridden the ApplySettingsAndGoBackAsync method in ProtonAccountSettingsPageViewModel.cs to handle NeedAdditionalAuthInfo by clearing errors for MailboxPassword and adding an appropriate message.
> [!NOTE]
>
>
> …
=> fix: add exception handling to ApplySettingsAndGoBackAsync

.github/actions/assign-version/action.yml, .github/actions/install-prerequisites/action.yml, .github/configurations/build.json, .github/configurations/publish-desktop-app.json, .github/configurations/publish-mac-catalyst-pkg.json, .github/workflows/build.yml, .github/workflows/publish-desktop-app.yml, .github/workflows/publish-desktop-binaries.yml, .github/workflows/publish-desktop-snap.yml, .github/workflows/publish-mac-catalyst-pkg.yml, .github/workflows/publish.yml
- Bump `finebits/github-actions` from v2.0.0 to v3.0.0
- Modify `install-prerequisites`, `assign-version` actions
- Change the usage of the `finebits/github-actions/toolset/select-configuration` action
- Fix iOS and Mac Catalyst builds
> [!NOTE]
>
>
> - `build` - changes related to …
=> ci: update workflows

.github/configurations/publish-desktop-binaries.json
- Publish a binary for windows arm64
> [!NOTE]
>
>
> - `chore` - …
=> ci: add publish win-arm64

.github/actions/assign-version/action.yml, .github/workflows/publish-desktop-app.yml, .github/workflows/publish-desktop-binaries.yml, .github/workflows/publish-desktop-snap.yml, .github/workflows/publish-mac-catalyst-pkg.yml
- Change the version format in the artifact name
> [!NOTE]
>
>
> …
=> ci: change artifact name

.github/configurations/build.json, src/Eppie.App/.run/Eppie.App.run.xml, src/Eppie.App/Directory.Packages.props, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj, src/Eppie.App/Eppie.App/Eppie.App.csproj
Closes #510
- Bumps `CommunityToolkit.Uwp.Controls.TokenizingTextBox` from 8.1.240916 to 8.2.250402
- Bumps `CommunityToolkit.WinUI.Controls.TokenizingTextBox` from 8.1.240916 to 8.2.250402
- Bumps `Microsoft.UI.Xaml` from 2.8.6 to 2.8.7
- Change Windows version to 10.0.19041
> [!NOTE]
>
>
> - …
=> build: bump TokenizingTextBox nuget

src/Eppie.App/Directory.Packages.props, src/Tests/Eppie.App.ViewModels.Tests/ContactComparerTests.cs, src/Tests/Eppie.App.ViewModels.Tests/Eppie.App.ViewModels.Tests.csproj
Related to #672
- Updates CommunityToolkit.Mvvm from 8.2.2 to 8.4.0
- Updates EmailValidation from 1.2.0 to 1.3.0
- Updates Microsoft.Xaml.Behaviors.WinUI.Managed from 2.0.9 to 3.0.0
- Updates Microsoft.Xaml.Behaviors.Uwp.Managed from 2.0.1 to 3.0.0
- Updates System.IdentityModel.Tokens.Jwt from 8.3.0 to 8.9.0
- Updates Uno.Toolkit.UI from 6.1.8 to 6.4.6
- Updates Microsoft.NET.Test.Sdk from 17.6.0 to 17.13.0
- Updates NUnit from 3.13.3 to 4.3.2
- Updates NUnit3TestAdapter from 4.5.0 to 5.0.0
- Updates NUnit.Analyzers from 3.6.1 to 4.7.0
- Updates coverlet.collector from 6.0.0 to 6.0.4
- Fixes build errors
> [!NOTE]
>
>
> …
=> build: bump nugets

src/Eppie.App/Directory.Packages.props
=> build(deps): Bump to M.E.AI 9.4.3-preview.1.25230.7

.github/CODEOWNERS, src/Eppie.App/Directory.Packages.props
Related to #679 
Add codeowners.
> [!NOTE]
>
> …
=> ci: add codeowners

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json, src/Eppie.App/Eppie.App/Platforms/Desktop/Program.cs, src/Eppie.App/global.json
Related to #513, #677
- Bumps **Uno.Sdk** from 5.6.54 to 6.0.67
- Fixing build errors
> [!NOTE]
>
> …
=> build: bump Uno.Sdk to 6.0.67

src/Eppie.App/Directory.Packages.props
Related to #672
Updates Microsoft.Extensions.AI.Abstractions to M.E.AI 9.5.0-preview.1.25262.9
> [!NOTE]
>
> …
=> build(deps): Bump to M.E.AI 9.5.0-preview.1.25262.9

src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs, src/Eppie.App/Eppie.App.Shared/App.xaml.cs, src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, src/Eppie.App/Eppie.App.Shared/Helpers/EppieHost.UWP.cs, src/Eppie.App/Eppie.App.Shared/Helpers/EppieHost.Uno.cs, src/Eppie.App/Eppie.App.Shared/Helpers/EppieHost.cs
Related to #330
- Create `Host` configuration helper
- Move `Host` creation to shared project
UWP project cannot build `Host` until [migration to .net9](https://github.com/Eppie-io/Eppie-App/issues/351) is complete. 
> [!NOTE]
>
>
> - `build` - changes related to **the build of the project** and …
=> feat: configure Eppie Host

src/Eppie.App/Directory.Packages.props, src/Eppie.App/Eppie.App.Shared/App.xaml.cs, src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, src/Eppie.App/Eppie.App.Shared/Logging/LogConfiguration.cs, src/Eppie.App/Eppie.App.Shared/Services/ErrorHandler.cs, src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, src/Eppie.App/Eppie.App/Eppie.App.csproj
Related to #273
- Configure the `LoggerFactory` using `Serilog`
- Pass `LoggerFactory` to `TuviMailCore`
> [!NOTE]
>
> …
=> feat: configure logging

src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, src/Eppie.App/Eppie.App.Shared/Helpers/PlatformTools.cs, src/Eppie.App/Eppie.App.Shared/Logging/LogConfiguration.cs
Related to #273
- Add a property to the log with information about the application platform.
> [!NOTE]
>
> …
=> feat: add Platform property to log

src/Eppie.App/Directory.Packages.props, src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, src/Eppie.App/Eppie.App.Shared/Logging/HashTransformOperator.cs, src/Eppie.App/Eppie.App.Shared/Logging/LogConfiguration.cs, src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, src/Eppie.App/Eppie.App/Eppie.App.csproj
Related to #273
- Hide Email, IBAN and Credit Card information from the log.
> [!NOTE]
>
> …
=> feat: hide sensitive information in the log

src/Eppie.App/Directory.Packages.props, src/Eppie.App/Eppie.App.Shared/Logging/LogConfiguration.cs, src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, src/Eppie.App/Eppie.App/Eppie.App.csproj
Related to #273
- Add exception details and custom properties that are not output in `Exception.ToString()` to log.
> [!NOTE]
>
> …
=> feat: add exception details to log

src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw, src/Eppie.App/Eppie.App.Shared/Services/LauncherService.cs, src/Eppie.App/Eppie.App.Shared/Services/LocalSettingsService.cs, src/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml, src/Eppie.App/Eppie.App.ViewModels/Services/ILauncherService.cs, src/Eppie.App/Eppie.App.ViewModels/Services/ILocalSettingsService.cs, src/Eppie.App/Eppie.App.ViewModels/SettingsPageViewModel.cs
#273 
Add open logs folder button.
> [!NOTE]
>
> …
=> feat: add open logs folder button

src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw, src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, src/Eppie.App/Eppie.App.Shared/Services/AppStoreService.cs, src/Eppie.App/Eppie.App.Shared/Services/LocalSettingsService.cs, src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/SupportDevelopmentControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/SupportDevelopmentControl.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw, src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/Services/IAppStoreService.cs, src/Eppie.App/Eppie.App/Services/AppStoreService.cs
N/A
Change support development button.
> [!NOTE]
>
> …
=> fix: change support development button

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json, src/Eppie.App/Eppie.App/Platforms/Desktop/Program.cs, src/Eppie.App/global.json
Close #677
> [!NOTE]
>
>
> - `chore` - something that **doesn't fit** the other …
=> build: migrating to Uno Platform 6.0

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json, src/Eppie.App/global.json
Related to #513
- Bumps **Uno.Sdk** from 6.0.67 to 6.0.110
> [!NOTE]
>
>
> - …
=> build: bump uno sdk

src/Eppie.App/Eppie.App/Platforms/WebAssembly/Program.cs
Closes  #720
- Update WebAssembly platform files according to Uno 6 template
> [!NOTE]
>
> …
=> build: update wasm

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj, src/Eppie.App/Eppie.App/Eppie.App.csproj
Related to #657
- Update WebView2 control
- To use on Linux, you'll need to install [libs](https://platform.uno/docs/articles/controls/WebView.html#x11-specifics)
- I have [this](https://redirect.github.com/unoplatform/uno/issues/20719#issue-3121835076) error on WSL (ubuntu-24.04)
> [!NOTE]
>
>
> …
=> feat: add html email display to the desktop app

src/Eppie.App/Directory.Packages.props, src/Eppie.App/Eppie.App.Shared/App.xaml, src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs, src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj, src/Eppie.App/Eppie.App.UWP/Models/BrandLoader.cs, src/Eppie.App/Eppie.App/Eppie.App.csproj, src/Eppie.App/Eppie.App/Models/BrandLoader.cs
Related to #377
- Remove `Uno.Toolkit.UI` package from Uno and UWP projects
- Remove unused `using`
> [!NOTE]
>
>
> - `docs` - changes in **documentation** or …
=> refactor: remove Uno.Toolkit.UI package

src/Eppie.App/Eppie.App/Eppie.App.csproj
Close  #514
- Remove the hotfix since the original bug has been fixed
> [!NOTE]
>
> …
=> chore: remove webview2 hotfix

.github/configurations/publish-desktop-app.json, .github/configurations/publish-desktop-binaries.json, .github/configurations/publish-desktop-span.json, src/Eppie.App/Directory.Build.targets, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj, src/Eppie.App/Eppie.App/Eppie.App.csproj
References  #609
- Simplify the code for publishing the Desktop app
> [!NOTE]
>
> …
=> refactor: change the override of the TargetFrameworks property

src/Eppie.App/Eppie.App/Eppie.App.csproj
- Simplify the code for overriding the **UnoFeatures** property
> [!NOTE]
>
>
> - `docs` - changes in **documentation** or just **comments** …
=> refactor: change the definition of UnoFeatures

src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw, src/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/WhatsNewControl.xaml
N/A
Fix about page.
> [!NOTE]
>
>
> - `chore` - something that **doesn't fit** …
=> fix: fix about page

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/DialogBehavior.cs, src/Eppie.App/Eppie.App.ViewModels/SeedRestorePageViewModel.cs
N/A
Fix ApplyCommand.
> [!NOTE]
>
>
> - `chore` - something that **doesn't fit** …
=> fix: fix ApplyCommand

src/Eppie.App/Eppie.App/Eppie.App.csproj, src/Eppie.App/Eppie.App/Platforms/Android/AndroidManifest.xml
N/A
Add permission internet.
> [!NOTE]
>
> …
=> chore: add permission internet

src/Eppie.App/Eppie.App/Eppie.App.csproj
N/A
Fix AndroidKeyStore.
> [!NOTE]
>
> …
=> chore: fix AndroidKeyStore

.github/workflows/format.yml
- exclude the file `./src/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs` from checking
> [!NOTE]
>
>
> - `docs` - changes in **documentation** or …
=> ci: update format.yml workflow

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/ConvertersDictionary.xaml
N/A
Changed Foreground and FontWeight properties in the "AccentTextStyle" to use "AccentTextFillColorPrimaryBrush" and set FontWeight to Bold for improved styling.
> [!NOTE]
>
> …
=> fix: Update AccentTextStyle in ConvertersDictionary.xaml

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json, src/Eppie.App/global.json
Related to #513
- Bumps **Uno.Sdk** from 6.0.146 to 6.1.23
> [!NOTE]
>
>
> - …
=> build: bump Uno SDK to 6.1.23

.github/configurations/publish-desktop-app.json
- remove `PublishSingleFile` property
> [!NOTE]
>
>
> - `chore` …
=> ci: fix publish macOS desktop

.github/configurations/publish-desktop-app.json, .github/workflows/publish-desktop-app.yml
- To create the osx-x64 app bundle, the macOS 13 image is used.
> [!NOTE]
>
>
> - `docs` - changes in **documentation** or just **comments** …
=> ci: fix osx-x64 app bundle

src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw, src/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml, src/Eppie.App/Eppie.App.Shared/Views/ProtonAccountSettingsPage.xaml, src/Eppie.App/Eppie.App.ViewModels/AccountSettingsModel.cs, src/Eppie.App/Eppie.App.ViewModels/AccountSettingsPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/BaseAccountSettingsPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/DecentralizedAccountSettingsPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/NewMessagePageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/ProtonAccountSettingsModel.cs, src/Eppie.App/Eppie.App.ViewModels/SettingsPageViewModel.cs
N/A
Improve hybrid and dec.
> [!NOTE]
>
> …
=> refactor: improve hybrid and dec

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailsInputControl.xaml.cs, src/Eppie.App/Eppie.App.ViewModels/NewMessagePageViewModel.cs
N/A
Fix standard address.
> [!NOTE]
>
> …
=> fix: standard address

src/Eppie.App/Eppie.App.ViewModels/BaseAccountSettingsPageViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/DecentralizedAccountSettingsPageViewModel.cs
N/A
Improve keys.
> [!NOTE]
>
> …
=> refactor: improve keys

src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs, src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs
N/A
- Updated `DataContextChangedImpl` in `BasePage` to use `SetAIServiceProvider` for better flexibility in managing AI service providers.
- Added methods for setting `Core` and `AIService` providers in `BaseViewModel`, enhancing encapsulation and testability.
- Removed old methods related to direct AIService assignment, promoting a more abstract approach.
- Improved `AIAgentProcessMessageAsync` by using a local variable for AI service and added null checks to prevent runtime errors.
> [!NOTE]
>
>
> - `perf` - …
=> refactor: AI service handling

README.md
N/A
Add GitHub release downloads badge.
> [!NOTE]
>
> …
=> Add GitHub release downloads badge

src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json, src/Eppie.App/global.json
Related to #513
- Bumps **Uno.Sdk** from 6.1.23 to 6.2.29
> [!NOTE]
>
>
> - …
=> build: bump Uno.Sdk to 6.2.29

src/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs, src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs, src/Eppie.App/Eppie.App.Shared/App.xaml.cs
N/A
- Set minimum window size (for UWP 500x486 in other cases 864x486)
> [!NOTE]
>
> …
=> feat: configure minimum window size

src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw
N/A
Fix resource string.
> [!NOTE]
>
> …
=> fix: fix resource string

src/Eppie.App/Eppie.App.ViewModels/DecentralizedAccountSettingsPageViewModel.cs
N/A
Fix account update.
> [!NOTE]
>
> …
=> fix: fix account update

src/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NewAccountSettingsControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NewAccountSettingsControl.xaml.cs, src/Eppie.App/Eppie.App.ViewModels/AccountSettingsPageViewModel.cs
N/A
- Add new properties for settings mode and server expansion.
- Implement loading indicator for settings application.
- Introduce visibility logic for custom settings section.
- Update validation logic to manage server expansion states.
> [!NOTE]
>
>
> - `build` - changes related to **the build …
=> feat: add account settings modes

src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, src/Eppie.App/Eppie.App.Shared/StaticResources/BrandResource.cs, src/Eppie.App/Eppie.App.Shared/StaticResources/StaticResources.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NewAccountSettingsControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw
N/A
- Introduce BrandResource class to encapsulate brand information.
- Enhance XAML resources with AttachmentConverter and BrandResource.
- Update homepage links in the UI to use dynamic data from BrandResource.
- Improve localization by adding new resource strings for email input.
> [!NOTE]
>
> …
=> feat: add brand resource

src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems, src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml.cs, src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs
Related to #840
- Create new application settings.
> [!NOTE]
>
>
> - `chore` - …
=> feat: add draft of AppSettingsPage 

src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml.cs, src/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml.cs
Related to  #840
- Add some logic
> [!NOTE]
>
> …
=> feat: add some logic to AppSettingsPage

src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw, src/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AccountSettingsControl.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NewAccountSettingsControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NewAccountSettingsControl.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw
Related to #839
- Change the layout of the controls
- Update string resources
> [!NOTE]
>
> …
=> refactor: email settings control

src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw, src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml
Related to #840
- Add a settings option to view the seed phrase.
> [!NOTE]
>
>
> …
=> feat: settings seedphrase

src/Eppie.App/Eppie.App.Shared/Views/BitcoinAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/EppieAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressControl.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressSettingsView.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailSettingsControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
Related to #861
- Create `AddressControl`
- Use this control in `BitcoinAddressSettingsPage`, `EppieAddressSettingsPage` and `EmailSettingsControl` xaml files
> [!NOTE]
>
> …
=> feat: add address control

src/Eppie.App/Eppie.App.Shared/Views/DecentralizedAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/DecentralizedAddressSettingsPage.xaml.cs, src/Eppie.App/Eppie.App.Shared/Views/EthereumAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/DecentralizedAccountSettingsControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/DecentralizedAccountSettingsControl.xaml.cs, src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs, src/Eppie.App/Eppie.App.ViewModels/DecentralizedAddressSettingsPageViewModel.cs
Related to #861
- Create `EthereumAddressSettingsPage`
- Mark the old decentralized address settings code
> [!NOTE]
>
> …
=> feat: make ethereum address settings

src/Eppie.App/Eppie.App/Models/BrandLoader.cs
#875 
* Fix BrandLoader key inconsistency: change GitHubUrl to GitHub
> [!NOTE]
>
> …
=> fix: `BrandLoader` key inconsistency causing GetGitHub() to fail

src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/BitcoinAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/EmailAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/EppieAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/EthereumAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressControl.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressSettingsView.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AdvancedSettingsControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailSettingsControl.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/OptionControl.xaml.cs
Related to #839, #840, #861
- Add `ContentProperty` to `AddressControl`
- Add `ContentProperty` to `AddressSettingsView`
- Add `ContentProperty` to `OptionControl`
- Update **xaml** files that uses these controls
> [!NOTE]
>
>
> - `build` - changes related to **the build of the project** and …
=> refactor: add content property

src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml
#851 
* Replace hardcoded seed phrase text with 'Not implemented'
> [!NOTE]
>
> …
=> chore: replace hardcoded seed phrase text with "Not implemented" 

src/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailSettingsControl.xaml
N/A
* Fix app name binding in AboutPage.xaml to use AppName property
* Fix app name binding in EmailSettingsControl.xaml signature section
> [!NOTE]
>
>
> - …
=> fix: fix application name not displayed in About page and Email Settings

src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw, src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw
N/A
- Update field and button labels for better precision.
- Add security warnings to seed phrase and key descriptions.
- Simplify and unify translation-related strings.
- Fix punctuation and improve phrasing in hybrid address notes.
- Enhance clarity in PGP key generation descriptions.
> [!NOTE]
>
>
> - `style` - changes in **code styles** and no changes in …
=> refactor: improve text clarity and consistency

.github/workflows/publish-desktop-snap.yml, packages/snap/snapcraft.template.yaml
Related to  #609
- Change snap package **confinement** to **strict**
> [!NOTE]
>
> …
=> ci: update snap package publication

README.md
#895 
* Fix typos in README.md: ambitiois→ambitious, subscripe→subscribe
* fix: fix review
> [!NOTE]
>
> …
=> fix: fix typos in README.md

src/Eppie.App/Eppie.App.Shared/Views/BitcoinAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/EppieAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.Shared/Views/EthereumAddressSettingsPage.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressSettingsView.xaml, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressSettingsView.xaml.cs, src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw, src/Eppie.App/Eppie.App.ViewModels/SelectServicePageViewModel.cs
N/A
- Introduce `JoinWaitingListCommand` to manage new button behavior.
- Bind the command to address settings pages for consistency.
- Update "Apply" button visibility logic to depend on the new command.
- Add a dedicated "Join Waiting List" button with dynamic visibility.
- Extend localization resources with text for the new button.
> [!NOTE]
>
>
> - `style` …
=> feat: add "Join Waiting List" button functionality
